# Generated by Django 6.1 on 2026-09-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TareasProyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('es_tarea', models.BooleanField(default=False)),
                ('es_proyecto', models.BooleanField(default=False)),
                ('publico', models.BooleanField(default=False)),
            ],
        ),
    ]
