# Generated by Django 6.1 on 2026-09-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareasproyectos',
            name='publico',
        ),
        migrations.AddField(
            model_name='tareasproyectos',
            name='privado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tareasproyectos',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
