# Generated by Django 6.1 on 2026-09-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_tareasproyectos_publico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareasProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('es_tarea_completa', models.BooleanField(default=False)),
                ('numero_integrantes', models.IntegerField(default=1)),
                ('privado', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TareasProyectos',
        ),
    ]
