# Generated by Django 6.1 on 2026-09-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tareasproyecto_delete_tareasproyectos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('es_proyecto_completo', models.BooleanField(default=False)),
                ('integrantes', models.IntegerField(default=1)),
                ('privado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('es_tarea_completa', models.BooleanField(default=False)),
                ('integrantes', models.IntegerField(default=1)),
                ('privado', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TareasProyecto',
        ),
    ]
