# Generated by Django 6.1 on 2026-09-06 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_proyecto_tarea_delete_tareasproyecto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='integrantes',
            new_name='integrantes_totales',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='es_proyecto_completo',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='es_tarea_completa',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='integrantes',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='privado',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_limite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tarea',
            name='asignado_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En progreso'), ('completado', 'Completado')], default='pendiente', max_length=50),
        ),
        migrations.AddField(
            model_name='tarea',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='core.proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
